### ISSUE TITLE
Invalid Hook call

### ISSUE THREAD

**Issue by hungtd97** [ruilisi/react-media-previewer#3]
When using PreviewModal I got this error. Should we need to maintain this package with the latest React? This's really nice module

> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem

Version: 1.3.7
React Version: 18.2.0

**Comment by fybchristasker** [comment]
@hungtd97 Maybe you should refer to it in the functional component, otherwise it will report this error, which may not depend on the react version, or could you provide a reproduce？

**Comment by hungtd97** [comment]
@fybchristasker Yes I used in function component, I found some similar issues on StackOverflow https://stackoverflow.com/questions/56663785/invalid-hook-call-hooks-can-only-be-called-inside-of-the-body-of-a-function-com
So I guess it conflicted by React version

**Comment by fybchristasker** [comment]
@hungtd97 Ok, thanks for your feedback, the new version is on the way, lets wait and see.
